name: Simple Startup

on:
  push:
    branches: [main]
#  schedule:
#    - cron: '* * * * *'
    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-16.04
    steps:
    - name: Print a greeting
      run: echo Hello there!!
